theme = "awesome-identity"
baseURL = "https://joshkraan.com"
title = "Josh Kraan"
languageCode = "en-US"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

# googleAnalytics = 

# Add your own params here
[params]
  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = ""

## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Engineering Physics Student"
  keywords = "josh, joshua, kraan, student, engineering"
  #images = [
  #  "/images/profile.jpg"
  #]

## Profile Configurations
[params.profile]
  # portrait = "/images/portrait-default.png"
  firstname = "Josh"
  lastname = "Kraan"
  title = "Engineering Physics Student"
  bio = """ University of British Columbia """

## Contacts Configurations
[params.contacts]
  email = "contact@joshkraan.com"
  github = "joshkraan"
  # twitter = "john.smith"
  # facebook = "john.smith"
  linkedin = "joshkraan"
  # instagram = "john.smith"
  # stackoverflow = "7919458"
  # keybase = "john.smith"
  # medium = "john.smith"

[[params.actions]]
  name = "Download my Resume"
  url = "/resume.pdf"


## Footer Configurations
[params.footer]
  copyright = "© 2019 Josh Kraan"
  poweredBy = false
